name: Daily newsletter subscriber list
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send updated list of newsletter subscribers
        run: |
          curl --request POST \
          --url 'https://www.haleyfairchild.com/api/subscribers' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
